In [1]:
import numpy as np
import time

In [2]:
def NSquare(number) :
    start = time.time()
    if (number % 2) == 0 : 
        N = number+1
    else : 
        N = number
    magic_square = np.zeros((N,N), dtype=int)
    n = 1
    i, j = 0, N//2
    while n <= N**2:
        magic_square[i, j] = n
        n += 1
        newi, newj = (i-1) % N, (j+1)% N
        if magic_square[newi, newj]:
            i += 1
        else:
            i, j = newi, newj
    end = time.time()
    print(magic_square)
    print("\nExecution time : ", round(end-start,2),"s")
    print("--------------------------")

In [3]:
print("Starting N-Square problem with N = 5 ...")
print("--------------------------")
NSquare(5)

Starting N-Square problem with N = 5 ...
--------------------------
[[17 24  1  8 15]
 [23  5  7 14 16]
 [ 4  6 13 20 22]
 [10 12 19 21  3]
 [11 18 25  2  9]]

Execution time :  0.0 s
--------------------------


In [4]:
print("Starting N-Square problem with N = 7 ...")
print("--------------------------")
NSquare(7)

Starting N-Square problem with N = 7 ...
--------------------------
[[30 39 48  1 10 19 28]
 [38 47  7  9 18 27 29]
 [46  6  8 17 26 35 37]
 [ 5 14 16 25 34 36 45]
 [13 15 24 33 42 44  4]
 [21 23 32 41 43  3 12]
 [22 31 40 49  2 11 20]]

Execution time :  0.0 s
--------------------------


In [5]:
print("Starting N-Square problem with N = 9 ...")
print("--------------------------")
NSquare(9)

Starting N-Square problem with N = 9 ...
--------------------------
[[47 58 69 80  1 12 23 34 45]
 [57 68 79  9 11 22 33 44 46]
 [67 78  8 10 21 32 43 54 56]
 [77  7 18 20 31 42 53 55 66]
 [ 6 17 19 30 41 52 63 65 76]
 [16 27 29 40 51 62 64 75  5]
 [26 28 39 50 61 72 74  4 15]
 [36 38 49 60 71 73  3 14 25]
 [37 48 59 70 81  2 13 24 35]]

Execution time :  0.0 s
--------------------------


In [6]:
print("Starting N-Square problem with N = 11 ...")
print("--------------------------")
NSquare(11)

Starting N-Square problem with N = 11 ...
--------------------------
[[ 68  81  94 107 120   1  14  27  40  53  66]
 [ 80  93 106 119  11  13  26  39  52  65  67]
 [ 92 105 118  10  12  25  38  51  64  77  79]
 [104 117   9  22  24  37  50  63  76  78  91]
 [116   8  21  23  36  49  62  75  88  90 103]
 [  7  20  33  35  48  61  74  87  89 102 115]
 [ 19  32  34  47  60  73  86  99 101 114   6]
 [ 31  44  46  59  72  85  98 100 113   5  18]
 [ 43  45  58  71  84  97 110 112   4  17  30]
 [ 55  57  70  83  96 109 111   3  16  29  42]
 [ 56  69  82  95 108 121   2  15  28  41  54]]

Execution time :  0.0 s
--------------------------


In [7]:
print("Starting N-Square problem with N = 13 ...")
print("--------------------------")
NSquare(13)

Starting N-Square problem with N = 13 ...
--------------------------
[[ 93 108 123 138 153 168   1  16  31  46  61  76  91]
 [107 122 137 152 167  13  15  30  45  60  75  90  92]
 [121 136 151 166  12  14  29  44  59  74  89 104 106]
 [135 150 165  11  26  28  43  58  73  88 103 105 120]
 [149 164  10  25  27  42  57  72  87 102 117 119 134]
 [163   9  24  39  41  56  71  86 101 116 118 133 148]
 [  8  23  38  40  55  70  85 100 115 130 132 147 162]
 [ 22  37  52  54  69  84  99 114 129 131 146 161   7]
 [ 36  51  53  68  83  98 113 128 143 145 160   6  21]
 [ 50  65  67  82  97 112 127 142 144 159   5  20  35]
 [ 64  66  81  96 111 126 141 156 158   4  19  34  49]
 [ 78  80  95 110 125 140 155 157   3  18  33  48  63]
 [ 79  94 109 124 139 154 169   2  17  32  47  62  77]]

Execution time :  0.0 s
--------------------------
